item7/item7/urls.py
from django.conf.urls import url
from django.contrib import admin
from main import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
]

item7/main/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    isbn = models.CharField(max_length=255)

    class Meta:
        db_table = 'book'

    def __str__(self):
        return self.title


class List(models.Model):
    name = models.CharField(max_length=255)
    books = models.ManyToManyField(Book, through='BookList')

    class Meta:
        db_table = 'list'

    def __str__(self):
        return self.name


class BookList(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    list = models.ForeignKey(List, on_delete=models.CASCADE)
    order = models.IntegerField(default=1)
    comment = models.TextField()

    class Meta:
        db_table = 'book_list'
        ordering = ['order']

    def __str__(self):
        return self.book.title + ' in ' + self.list.name

item7/main/views.py
from django.shortcuts import render

from main.models import List


def index(request):
    lists = List.objects.all()
    return render(request, 'index.html', {'lists': lists})

item7/main/templates/index.html
{% extends 'layout.html' %}

{% block content %}
    <h1 class="text-center">Books Top Lists</h1>

    <p class="text-center"><a href="/admin">Manage Lists</a><br/>
    <span class="text-muted">Login: admin, Password: adminpassword</span> </p>

    <div class="lists row">
        {% for list in lists %}
            <div class="col-sm-6">
                <h3 class="text-center">{{ list.name }}</h3>
                {% for list_item in list.booklist_set.all %}
                    <div class="list-item">
                        <span class="rating-number">{{ list_item.order }}</span>
                        <p>
                            <strong>{{ list_item.book.title }}</strong><br/>
                            <span>by {{ list_item.book.author }}</span>
                            <span style="margin-left: 10px;">ISBN: {{ list_item.book.isbn }}</span>
                        </p>
                        <p>Comment:<br/>{{ list_item.comment }}</p>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>

{% endblock %}

item7/main/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>

    <style>
        .lists{
            margin-top: 40px;
        }

        .list-item{
            position: relative;
            padding: 20px 20px 20px 40px;
            max-width: 400px;
            margin: 0 auto;
        }

        .rating-number{
            position: absolute;
            font-size: 30px; line-height: 30px;
            left: 0; top: 50%; margin-top: -15px;
        }
    </style>

</head>
<body>
    <div class="wrap">
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>